import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "@/app/components/Header"
import Footer from "@/app/components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {" "}
        <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-between min-h-screen p-8 font-[family-name:var(--font-geist-sans)]">
          <Header />

          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
