import { OpenAI } from "openai"
import { OPENAI_API_KEY, META_MODEL } from "./config.js"

const openaiMeta = new OpenAI({ apiKey: OPENAI_API_KEY })

const promptsv1 = [
  "Tell us about a new character for the world.",
  "Summarize an existing lore prompt.",
  "Tell us about a new location for the world.",
  "Tell us about a prominent family in the world.",
  "Tell us about an organization in this world.",
  "Tell us about a new event for the world.",
  "Tell an amusing anecdote about a character we've met in the world.",
  "Give us more information about a character in the world.",
  "Give us a life story of a character in the world.",
  "Describe a normal day in the life of a character in the world.",
  "Describe an occupation in the world.",
  "Describe a rumor going around in the world.",
  "Tell us something random and interesting about the world.",
  "Tell us about the logistics of an existing location in the world.",
  "Tell us about the economy of an existing location in the world.",
  "Tell us about the culture of an existing location in the world.",
  "Tell us about the history of an existing location in the world.",
  "Tell us more about the global politics of the world.",
  "Tell us about the geography of the world.",
  "Tell us about the flora and fauna of the world.",
  "Tell us about the geopolitics of the world.",
  "Tell us about a nearby country to New Caspian.",
  "Tell us about a hobby or pastime in the world.",
  "Tell us about a sport in the world.",
  "Describe a major technological innovation or scientific breakthrough in the world.",
  "Tell the story of a myth or folktale that many citizens believe.",
  "Describe a black market or underground network operating in the world.",
  "Explain a major philosophical system practiced by people in the world.",
  "Describe a political scandal or controversy that shook public opinion.",
  "Tell us about a holiday or major public festival in the world.",
  "Describe a famous piece of art, literature, or music created in this world.",
  "Tell us about a dangerous place most people avoid — and why it is feared.",
  "Describe a criminal syndicate or rogue group causing problems in the world.",
  "Tell us about a forgotten hero or historical figure and their legacy.",
  "Tell us about a prophecy or prediction that influences decisions in the world.",
  "Describe a typical meal or food tradition among the common people.",
  "Describe a medical practice, superstition, or method of healing used by the inhabitants.",
]

const promptsv2 = [
  "Expand significantly on the background and motivations of an existing character.",
  "Summarize and further elaborate on a previously created lore prompt.",
  "Provide extensive new details about an established location in the world.",
  "Deepen our understanding of a prominent family we've already encountered.",
  "Expand on the structure, goals, and notable figures of an existing organization.",
  "Provide more context and detail about an event previously mentioned in the lore.",
  "Share a detailed and amusing anecdote about a character already introduced.",
  "Offer an in-depth exploration of the personality, habits, or secrets of an existing character.",
  "Construct a comprehensive life story for an established character.",
  "Illustrate a richly detailed typical day in the life of an existing character.",
  "Expand significantly upon a previously mentioned occupation, detailing its nuances.",
  "Elaborate extensively on a rumor already circulating in the world.",
  "Provide additional interesting or unusual facts about previously established world details.",
  "Delve deeply into the logistics and infrastructure of a location we've already defined.",
  "Explain in greater detail the economy of a previously described location.",
  "Expand on the unique cultural practices and traditions of an established location.",
  "Provide an extensive historical background for a previously introduced location.",
  "Give us a deeper analysis of the existing global politics of the world.",
  "Offer detailed insights into the known geography of the established world.",
  "Expand significantly on previously mentioned flora and fauna of the world.",
  "Provide more context on existing geopolitical tensions or alliances in the world.",
  "Explore in detail the relationship between New Caspian and an already established neighboring country.",
  "Expand significantly on a previously mentioned hobby or pastime.",
  "Deepen our understanding of a previously introduced sport.",
  "Elaborate extensively on an existing technological innovation or scientific breakthrough.",
  "Provide additional layers of context or interpretation to an already told myth or folktale.",
  "Describe in detail the operations of a black market or underground network we've previously encountered.",
  "Expand significantly upon a philosophical system previously mentioned.",
  "Provide a deeper dive into a political scandal or controversy previously introduced.",
  "Offer more details about an existing holiday or major public festival.",
  "Expand on the significance, origin, and impact of a previously described piece of art, literature, or music.",
  "Deeply elaborate on the reasons why an established dangerous location is widely feared.",
  "Provide greater detail on the activities and leadership of a previously mentioned criminal syndicate.",
  "Offer more context about the legacy and impact of a previously introduced historical figure or hero.",
  "Expand upon a previously mentioned prophecy or prediction and its current influence.",
  "Describe additional details or cultural context around a previously introduced meal or food tradition.",
  "Expand on the previously described medical practices, superstitions, or healing methods.",
]

const prompts = [
  "Write a social media post revealing a surprising detail about an existing character.",
  "Summarize a viral post or thread based on something that happened in the world.",
  "Share a photo caption or story post that gives more details about an established location.",
  "Describe a trending post about a prominent family everyone knows about.",
  "Create a post by an organization showcasing their culture, scandals, or quirky side.",
  "Write a 'Throwback Thursday' post recounting a key event previously mentioned.",
  "Share a funny meme or inside joke about a character already introduced.",
  "Post a series of comments giving deeper insights into an existing character's habits or secrets.",
  "Create a heartfelt post where an established character shares their life story.",
  "Describe a typical 'Day in the Life' post from an existing character's perspective.",
  "Write a job advertisement or rant about an occupation already mentioned.",
  "Share a juicy rumor spreading on social media in the world.",
  "Write a logistics update or travel vlog entry about a known location.",
  "Share an economic infographic or thread breaking down a city's economy.",
  "Post a cultural tradition going viral from an existing location.",
  "Share a 'Today in History' post about a historic moment from the world.",
  "Write a political hot take or debate post about current world affairs.",
  "Post a travel photo album showing known geography in the world.",
  "Share a nature post or viral video featuring established flora or fauna.",
  "Write a diplomatic drama thread showing ongoing geopolitical tensions.",
  "Share a travel review of a nearby country already introduced.",
  "Post a trending video of a hobby or pastime from the world.",
  "Post a philosophical rant or inspirational quote based on a known worldview.",
  "Write a scandalous exposé about a political controversy that went viral.",
  "Describe photo posts or videos from a recent major holiday or festival.",
  "Share a viral clip of a famous piece of art, literature, or music.",
  "Write a criminal syndicate's anonymous post flexing their operations.",
  "Share a tribute post honoring a forgotten hero or historical figure.",
  "Post a food blog entry about a meal or culinary tradition from the world.",
  "Share a travel blog post about arriving at a new location in the world.",
  "Post a photo and caption from the road, capturing a small unexpected moment.",
  "Write a short travel diary entry reflecting on a cultural tradition just experienced.",
  "Describe a social media post sharing the food or drink the traveler tried today.",
  "Share a story about getting lost or taking an unplanned detour.",
  "Write a thread about a conversation the traveler had with a local.",
  "Post a reaction to a festival, parade, or public gathering the traveler stumbled upon.",
  "Share a moody late-night reflection post from the traveler in an unfamiliar place.",
  "Write a cautionary post sharing a hard-earned lesson or travel mistake.",
  "Share a nostalgic post looking back at a place the traveler is leaving behind.",
  "Describe a travel map update showing the current path and upcoming destinations.",
  "Write a post about the traveler visiting a historic site and sharing what they learned.",
  "Share a 'locals only' tip or hidden gem the traveler was lucky to discover.",
  "Write a post about encountering strange wildlife or unfamiliar natural wonders.",
  "Share a journal entry about crossing a tense border or navigating political tensions.",
  "Describe a warm, homesick post about missing familiar things from home.",
  "Write a short video description where the traveler teaches a few local phrases or customs.",
  "Post about surviving harsh weather or a natural disaster during the journey.",
  "Share a reflective final post about the lessons the traveler learned by the end of the journey.",
  "Post a group chat screenshot between travelers trying to meet up before a festival.",
  "Write a viral trend post where users are posting photos of their worst travel injuries.",
  "Create a mock news alert about a political scandal rocking a major city.",
  "Share a craigslist-style ad offering questionable 'guard duty' jobs for travelers passing through a border zone.",
  "Write a wiki page entry, but show it mid-edit with arguments in the comments.",
  "Write a trending meme format that pokes fun at a well-known historical event or figure from the world.",
  "Post an emergency weather alert forcing all travelers to shelter in place — hinting at larger environmental issues.",
  "Write a nostalgic farewell post as a traveler leaves a city they've grown attached to.",
]

export async function generateMetaPrompt(worldOverview: string): Promise<string> {
  // const resp = await openaiMeta.chat.completions.create({
  //   model: META_MODEL,
  //   messages: [
  //     { role: "system", content: "You are a creative AI that generates new world-building prompts." },
  //     { role: "user", content: `Based on the following world summary, suggest the next area to develop:\n${worldOverview}` },
  //   ],
  //   max_tokens: 100,
  // })
  // let content = resp.choices[0].message.content ?? ""
  // content = content.trim()

  // const chosenPrompt = prompts[Math.floor(Math.random() * prompts.length)]

  // content = `"${content}". Based on this, ${chosenPrompt}`

  // return content

  const chosenPrompt = prompts[Math.floor(Math.random() * prompts.length)]
  return chosenPrompt
}
